name: HTML5 Validation
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  validate:
    name: Validate HTML
    runs-on: ubuntu-latest
    env:
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0', '3.1']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Build website
      run: bundle exec middleman build -e production
    - name: Validate files with W3 Nu Validator
      uses: Cyb3r-Jak3/html5validator-action@v7.1.0
      with:
        root: build/
    - name: Upload log file
      uses: actions/upload-artifact@v2
      with:
        name: log
        path: log.log
