name: HTML5 Validation
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  validate:
    name: Validate HTML
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup Ruby using version from .ruby-version
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Build website
      run: bundle exec middleman build -e production
    - name: Validate files with W3 Nu Validator
      uses: Cyb3r-Jak3/html5validator-action@v7.1.0
      with:
        root: build/
    - name: Upload log file
      uses: actions/upload-artifact@v2
      with:
        name: log
        path: log.log
